---
profiles:
  default:
    network: Mainnet
    private_key: "0x001"
    public_key: "0x001"
    account: a6356966eb0b3d7cc1ff15a9a5b11026c577ea896609befd6e939fa7c796d8cc
    rest_url: "https://fullnode.mainnet.aptoslabs.com"
